#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  # pushing a single file
  - path: serilog-sinks-log4net.zip

  # pushing all *.nupkg files in build directory recursively
  - path: '**\*.nupkg'    