#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  # pushing all *.nupkg files in build directory recursively
  - path: '**\*.nupkg'    